# Generated by Django 3.1.2 on 2020-10-15 18:51

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=65)),
                ('last_name', models.CharField(max_length=65)),
                ('birth_date', models.DateField()),
                ('country_of_origin', django_countries.fields.CountryField(max_length=2)),
                ('study', models.CharField(choices=[('PH', 'Physics'), ('CH', 'Chemistry'), ('ME', 'Medicine'), ('ML', 'Modern languages'), ('MS', 'Music'), ('VA', 'Visual arts'), ('GD', 'Graphic design'), ('MC', 'Mechanical engineering'), ('CO', 'COmputing')], max_length=35)),
                ('job', models.BooleanField()),
            ],
        ),
    ]
